---
title: "Get FreeBSD"
sidenav: download
---

:url-rel: https://download.FreeBSD.org/releases
:url-snapshot: https://download.freebsd.org/snapshots

include::shared/releases.adoc[]
include::shared/en/urls.adoc[]

= Get FreeBSD

For general information about past, present and future releases, see link:../releases/[Release Information].

// This is raw html to allow for a display:flex layout. asciidoctor doesn't support it.
++++
<h2 style="margin-bottom: 0; padding-bottom: 0">Considerations Before Downloading</h2>
<div class="article-flex">
<div class="article-flex-item">
<h3>Version &amp; Branch</h3>
<p>You likely want the latest production <strong>RELEASE</strong> of FreeBSD. Other branches like CURRENT and STABLE are developer-focused and require expertise to use successfully.</p>
</div>
<div class="article-flex-item">
<h3>Architecture</h3>
<p>Most users of FreeBSD will have hardware for <strong>amd64</strong> or <strong>aarch64</strong>. If you're uncertain which to use, check the manufactuer's documentation for your CPU.</p>
</div>
<div class="article-flex-item">
<h3>Image Type</h3>
<p>For most cases, use <strong>bootonly</strong> if you have a network connection, <strong>dvd1</strong> if you don't. Some embedded platforms have their own images, e.g., Raspberry Pi. See release announcements and <a href="https://docs.freebsd.org/en/books/handbook/bsdinstall/#bsdinstall-installation-media">handbook</a> for details. </p>
</div>
</div>
++++

Combined, these three attributes make up the download file name which looks like:

* FreeBSD-VERSION-BRANCH-ARCHITECTURE-IMAGETYPE.format
* Example: FreeBSD-14.2-RELEASE-amd64-bootonly.iso

[[download]]
== Latest Releases

FreeBSD provides support for the latest major version ("production") and the previous major version ("legacy"). See link:/security/#sup[supported FreeBSD releases] for complete lifecycle details. If installing new, use the latest production release.

[[download-rel142]]
=== FreeBSD {rel142-current}-RELEASE

[.tblbasic]
[.tblDownload]
[options="header,footer"]
|===
|Installer |VM |SD Card 
a|
* link:{url-rel}/amd64/amd64/ISO-IMAGES/{rel142-current}/[amd64]
* link:{url-rel}/i386/i386/ISO-IMAGES/{rel142-current}/[i386]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[aarch64]
* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel142-current}/[armv7]
* link:{url-rel}/powerpc/powerpc/ISO-IMAGES/{rel142-current}/[powerpc]
* link:{url-rel}/powerpc/powerpc64/ISO-IMAGES/{rel142-current}/[powerpc64]
* link:{url-rel}/powerpc/powerpc64le/ISO-IMAGES/{rel142-current}/[powerpc64le]
* link:{url-rel}/powerpc/powerpcspe/ISO-IMAGES/{rel142-current}/[powerpcspe]
* link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel142-current}/[riscv64]

a|
* link:{url-rel}/VM-IMAGES/README.txt[README]
* link:{url-rel}/VM-IMAGES/{rel142-current}-RELEASE/amd64/Latest/[amd64]
* link:{url-rel}/VM-IMAGES/{rel142-current}-RELEASE/i386/Latest/[i386]
* link:{url-rel}/VM-IMAGES/{rel142-current}-RELEASE/aarch64/Latest/[aarch64]
* link:{url-rel}/VM-IMAGES/{rel142-current}-RELEASE/riscv64/Latest/[riscv64]
* link:{url-rel}/CI-IMAGES/{rel142-current}-RELEASE/amd64/Latest/[amd64] (BASIC-CI)
* link:{url-rel}/CI-IMAGES/{rel142-current}-RELEASE/aarch64/Latest/[aarch64] (BASIC-CI)

a|

Platform Specific

* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[PINE64]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[PINE64-LTS]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[ROCK64]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[ROCKPRO64]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[RPI] (3/4)

Generic

* link:{url-rel}/arm/armv7/ISO-IMAGES/{rel142-current}/[GENERICSD] (armv7)
* link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel142-current}/[GENERICSD] (riscv64)

3+|
link:../releases/#current[Released]: {rel142-current-date}

link:{u-rel142-notes}[Release Notes]
link:{u-rel142-readme}[Readme]
link:{u-rel142-hardware}[Hardware Compatibility List]
link:{u-rel142-installation}[Installation Instructions]
link:{u-rel142-errata}[Errata]
link:{u-rel142-signatures}[Signed Checksums]

|===

[[download-rel135]]
=== FreeBSD {rel135-current}-RELEASE
[.tblbasic]
[.tblDownload]
[options="header,footer"]
|===
|Installer |VM |SD Card 
a|
* link:{url-rel}/amd64/amd64/ISO-IMAGES/{rel135-current}/[amd64]
* link:{url-rel}/i386/i386/ISO-IMAGES/{rel135-current}/[i386]
* link:{url-rel}/powerpc/powerpc/ISO-IMAGES/{rel135-current}/[powerpc]
* link:{url-rel}/powerpc/powerpc64/ISO-IMAGES/{rel135-current}/[powerpc64]
* link:{url-rel}/powerpc/powerpc64le/ISO-IMAGES/{rel135-current}/[powerpc64le]
* link:{url-rel}/powerpc/powerpcspe/ISO-IMAGES/{rel135-current}/[powerpcspe]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[aarch64]
* link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel135-current}/[riscv64]

a|
* link:{url-rel}/VM-IMAGES/README.txt[README]
* link:{url-rel}/VM-IMAGES/{rel135-current}-RELEASE/amd64/Latest/[amd64]
* link:{url-rel}/VM-IMAGES/{rel135-current}-RELEASE/i386/Latest/[i386]
* link:{url-rel}/VM-IMAGES/{rel135-current}-RELEASE/aarch64/Latest/[aarch64]
* link:{url-rel}/VM-IMAGES/{rel135-current}-RELEASE/riscv64/Latest/[riscv64]
* link:{url-rel}/CI-IMAGES/{rel135-current}-RELEASE/amd64/Latest/[amd64] (BASIC-CI)
* link:{url-rel}/CI-IMAGES/{rel135-current}-RELEASE/aarch64/Latest/[aarch64] (BASIC-CI)

a|
* aarch64
* {blank}
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[PINE64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[PINE64-LTS]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[PINEBOOK]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[ROCK64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[ROCKPRO64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[RPI] (3/4)
* armv6/armv7
* {blank}
** link:{url-rel}/arm/armv7/ISO-IMAGES/{rel135-current}/[GENERICSD]
** link:{url-rel}/arm/armv6/ISO-IMAGES/{rel135-current}/[RPI-B]
* riscv64
* {blank}
** link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel135-current}/[GENERICSD]

3+|
link:../releases/#current[Released]: {rel135-current-date}

link:{u-rel135-notes}[Release Notes]
link:{u-rel135-readme}[Readme]
link:{u-rel135-hardware}[Hardware Compatibility List]
link:{u-rel135-installation}[Installation Instructions]
link:{u-rel135-errata}[Errata]
link:{u-rel135-signatures}[Signed Checksums]
|===

[[download-rel134]]
=== FreeBSD {rel134-current}-RELEASE
[.tblbasic]
[.tblDownload]
[options="header,footer"]
|===
|Installer |VM |SD Card 
a|
* link:{url-rel}/amd64/amd64/ISO-IMAGES/{rel134-current}/[amd64]
* link:{url-rel}/i386/i386/ISO-IMAGES/{rel134-current}/[i386]
* link:{url-rel}/powerpc/powerpc/ISO-IMAGES/{rel134-current}/[powerpc]
* link:{url-rel}/powerpc/powerpc64/ISO-IMAGES/{rel134-current}/[powerpc64]
* link:{url-rel}/powerpc/powerpc64le/ISO-IMAGES/{rel134-current}/[powerpc64le]
* link:{url-rel}/powerpc/powerpcspe/ISO-IMAGES/{rel134-current}/[powerpcspe]
* link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[aarch64]
* link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel134-current}/[riscv64]

a|
* link:{url-rel}/VM-IMAGES/README.txt[README]
* link:{url-rel}/VM-IMAGES/{rel134-current}-RELEASE/amd64/Latest/[amd64]
* link:{url-rel}/VM-IMAGES/{rel134-current}-RELEASE/i386/Latest/[i386]
* link:{url-rel}/VM-IMAGES/{rel134-current}-RELEASE/aarch64/Latest/[aarch64]
* link:{url-rel}/VM-IMAGES/{rel134-current}-RELEASE/riscv64/Latest/[riscv64]
* link:{url-rel}/CI-IMAGES/{rel134-current}-RELEASE/amd64/Latest/[amd64] (BASIC-CI)
* link:{url-rel}/CI-IMAGES/{rel134-current}-RELEASE/aarch64/Latest/[aarch64] (BASIC-CI)

a|
* aarch64
* {blank}
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[PINE64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[PINE64-LTS]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[PINEBOOK]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[ROCK64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[ROCKPRO64]
** link:{url-rel}/arm64/aarch64/ISO-IMAGES/{rel134-current}/[RPI] (3/4)
* armv6/armv7
* {blank}
** link:{url-rel}/arm/armv7/ISO-IMAGES/{rel134-current}/[GENERICSD]
** link:{url-rel}/arm/armv6/ISO-IMAGES/{rel134-current}/[RPI-B]
* riscv64
* {blank}
** link:{url-rel}/riscv/riscv64/ISO-IMAGES/{rel134-current}/[GENERICSD]

3+|
link:../releases/#current[Released]: {rel134-current-date}

link:{u-rel134-notes}[Release Notes]
link:{u-rel134-readme}[Readme]
link:{u-rel134-hardware}[Hardware Compatibility List]
link:{u-rel134-installation}[Installation Instructions]
link:{u-rel134-errata}[Errata]
link:{u-rel134-signatures}[Signed Checksums]
|===


[[download-snapshots]]
== Development Snapshots

Prior to RELEASE there are a series of branches that represent various phases in development and release engineering.

++++
<div style="display: flex; flex-wrap: wrap; gap: 0 30px">
<div style="flex: 1 1 45%">
++++

* RELEASE - FreeBSD as it inteded to be used. This is what most people will want.
** Receives support and patches
** Well documented
** Detailed release communication
* Pre-RELEASE - intended for development and testing. _Not for everyday use._
** link:https://docs.freebsd.org/en/books/handbook/cutting-edge/#current[CURRENT] – main development branch
** link:https://docs.freebsd.org/en/books/handbook/cutting-edge/#stable[STABLE] – for release engineering
** ALPHA, BETA, RC (release candidates) – increasing quality milestones within release engineering that lead up to the final release


++++
</div>
<div style="flex: 1 1 45%; min-width: 380px">

<div style="text-align: left; margin: 15px 0 0 15px;">The Path To A FreeBSD RELEASE</div>
++++

----
GIT SRC REPO      REVISION=   BRANCH=  
main              15.0        CURRENT
│
├─stable/14       14.3        STABLE
│ │
│ ├─releng/14.3   14.3        STABLE
│ │               14.3        ALPHA1
│ │               14.3        BETA1
│ │               14.3        RC1
│ │               14.3        RELEASE 
│ │               14.3        RELEASE-p1
│ │
│ ├─releng/14.4   14.4        STABLE
┊ ┊               …           …
----

++++
</div>
</div>
++++

See link:../snapshots/[FreeBSD Snapshot Releases].

=== {rel-head}-CURRENT

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel-head}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel-head}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel-head}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel-head}/[powerpc64], link:{url-snapshot}/powerpc/powerpc64le/ISO-IMAGES/{rel-head}/[powerpc64le], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel-head}/[powerpcspe], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel-head}/[armv7], link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel-head}/[aarch64], and link:{url-snapshot}/riscv/riscv64/ISO-IMAGES/{rel-head}/[riscv64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/amd64/Latest/[amd64], link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/i386/Latest/[i386], link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/aarch64/Latest/[aarch64], and link:{url-snapshot}/VM-IMAGES/{rel-head}-CURRENT/riscv64/Latest/[riscv64].

=== {rel142-current}-STABLE

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel142-current}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel142-current}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel142-current}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel142-current}/[powerpc64], link:{url-snapshot}/powerpc/powerpc64le/ISO-IMAGES/{rel142-current}/[powerpc64le], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel142-current}/[powerpcspe], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel142-current}/[armv7], link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel142-current}/[aarch64], and link:{url-snapshot}/riscv/riscv64/ISO-IMAGES/{rel142-current}/[riscv64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel142-current}-STABLE/amd64/Latest/[amd64], link:{url-snapshot}/VM-IMAGES/{rel142-current}-STABLE/i386/Latest/[i386], link:{url-snapshot}/VM-IMAGES/{rel142-current}-STABLE/aarch64/Latest/[aarch64], and link:{url-snapshot}/VM-IMAGES/{rel142-current}-STABLE/riscv64/Latest/[riscv64].

=== {rel135-current}-STABLE

Installer and SD card images are available for link:{url-snapshot}/amd64/amd64/ISO-IMAGES/{rel135-current}/[amd64], link:{url-snapshot}/i386/i386/ISO-IMAGES/{rel135-current}/[i386], link:{url-snapshot}/powerpc/powerpc/ISO-IMAGES/{rel135-current}/[powerpc], link:{url-snapshot}/powerpc/powerpc64/ISO-IMAGES/{rel135-current}/[powerpc64], link:{url-snapshot}/powerpc/powerpc64le/ISO-IMAGES/{rel135-current}/[powerpc64le], link:{url-snapshot}/powerpc/powerpcspe/ISO-IMAGES/{rel135-current}/[powerpcspe], link:{url-snapshot}/arm/armv6/ISO-IMAGES/{rel135-current}/[armv6], link:{url-snapshot}/arm/armv7/ISO-IMAGES/{rel135-current}/[armv7], link:{url-snapshot}/arm64/aarch64/ISO-IMAGES/{rel135-current}/[aarch64], and link:{url-snapshot}/riscv/riscv64/ISO-IMAGES/{rel135-current}/[riscv64].

VM images are available for link:{url-snapshot}/VM-IMAGES/{rel135-current}-STABLE/amd64/Latest/[amd64], link:{url-snapshot}/VM-IMAGES/{rel135-current}-STABLE/i386/Latest/[i386], link:{url-snapshot}/VM-IMAGES/{rel135-current}-STABLE/aarch64/Latest/[aarch64], and link:{url-snapshot}/VM-IMAGES/{rel135-current}-STABLE/riscv64/Latest/[riscv64].

[[install]]
== Installation

Options include:

* images
* direct download (anonymous FTP, and HTTPS).

Before downloading an entire distribution, please read the link:{handbook}bsdinstall/[installation guide].

If you plan to get FreeBSD via FTP or HTTPS, check the FreeBSD Handbook for link:{handbook}mirrors/#mirrors[suitable mirrors] for your region.

[[distribution]]
== Purchase FreeBSD Media

FreeBSD can be acquired on DVD from https://www.freebsdmall.com/[FreeBSD Mall], and other link:{handbook}mirrors/#mirrors-disc[DVD publishers].

[[apps]]
== Applications and Utility Software

=== The Ports Collection

A diverse collection of utility and application software that has been _ported_ to FreeBSD.

* link:../ports/[About FreeBSD Ports]
* https://www.freshports.org/[FreshPorts - a more advanced web interface to the Collection]
* link:{handbook}ports/[Installing Applications: Packages and Ports] in the FreeBSD Handbook
* Browse the Collection: https://cgit.freebsd.org/ports/tree/[FreeBSD ports Git repository] | https://download.freebsd.org/ports/[web].

For information about how _you_ can contribute _your_ favorite piece of software to the Collection, have a look at _link:{porters-handbook}[The Porter's Handbook]_ and _link:{contributing}[Contributing to FreeBSD]_.

++++
<!---
++++

[[derived]]
== FreeBSD-derived Operating System Distributions

FreeBSD is widely used as a building block for other commercial and open-source operating systems.
The projects below are of particular interest.

* https://www.truenas.com/[TrueNAS] is network attached storage (NAS) software that shares and protects data from modern-day threats like ransomware and malware. TrueNAS makes it easy for users and client devices to access shared data through virtually any sharing protocol.
* https://www.ghostbsd.org[GhostBSD] is derived from FreeBSD, and uses the GTK environment to provide a beautiful look and a comfortable experience on a modern BSD platform offering a natural and native UNIX(R)-like work environment.
* https://www.midnightbsd.org[MidnightBSD] was forked from FreeBSD 6.1 beta, and continues to use parts of more recent FreeBSD code bases. Developed with desktop users in mind, MidnightBSD includes everything that you would expect for your daily tasks: mail, web browsing, word processing, gaming, and much more.
* https://www.nomadbsd.org[NomadBSD] is a persistent live system for USB flash drives, based on FreeBSD. Together with automatic hardware detection and setup, it is configured to be used as a desktop system that works out of the box, but can also be used for data recovery, for educational purposes, or to test FreeBSD hardware compatibility.
* https://www.pfsense.org/[pfSense] is a FreeBSD-based customized distribution tailored for use as a firewall and router.

++++
-->
++++

[[past]]
== Archives

http://ftp-archive.FreeBSD.org/pub/FreeBSD-Archive/old-releases/[Past releases] of FreeBSD.
